# Generated by Django 2.2.4 on 2022-04-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='state',
        ),
    ]
