# Generated by Django 2.2.4 on 2022-04-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_remove_ninja_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='LastName',
            new_name='lastName',
        ),
    ]
